include:
  - remote: 'https://gitlab.cern.ch/c2mon/c2mon/-/raw/master/.gitlab-ci-templates/internal-gitlab-ci.yml'

# Get the settings file from c2mon project
before_script:
  - curl -O https://gitlab.cern.ch/c2mon/c2mon/raw/master/settings.xml
  
trigger_build:
  stage: sonar
  script:
    - "curl -X POST -F token=$TIM_WEB_UI_TOKEN -F ref=master https://gitlab.cern.ch/api/v4/projects/33220/trigger/pipeline"
  only:
  - master
