image: 
  name: gitlab-registry.cern.ch/industrial-controls/sw-infra/cc7-maven:jdk-11-mvn-3.6-1
  entrypoint: [""] 

stages:
- build
- deploy
- sonar

# Get the settings file from c2mon project
before_script:
  - curl -O https://gitlab.cern.ch/c2mon/c2mon/raw/master/settings.xml

# Fully build and publish master branch
build_and_publish:
  stage: build
  script:
    - mvn -q -B deploy --settings settings.xml -Ddependencies.set.direct -X
  only:
    - master

# Just run tests on feature branches
build:
  stage: build
  script:
    - mvn -B test -DskipDockerBuild -DskipDockerTag --settings settings.xml -Ddependencies.set.direct
  except:
    - master
  
trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F token=$TIM_WEB_UI_TOKEN -F ref=master https://gitlab.cern.ch/api/v4/projects/33220/trigger/pipeline"
  only:
  - master

sonar_preview:
  type: sonar
  script:
    - mvn -q -B compile sonar:sonar -Dmaven.test.skip=true -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0 --settings settings.xml --debug -X
  except:
    - master

quality_assurance:
  stage: sonar
  script:
    - mvn package sonar:sonar -Dsonar.host.url=$SONAR_URL -Dmaven.test.skip=true -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml --settings settings.xml
  only:
    - master
